# Generated by Django 4.1.3 on 2023-08-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('record_image_url', models.CharField(max_length=5000)),
                ('artist', models.CharField(max_length=100)),
                ('track_list', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('borrowed', models.BooleanField(default=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vinylvaultapi.genre')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=250)),
                ('profile_image_url', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinylvaultapi.record')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinylvaultapi.user')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinylvaultapi.user'),
        ),
        migrations.CreateModel(
            name='BorrowedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinylvaultapi.record')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinylvaultapi.user')),
            ],
        ),
    ]
