# Generated by Django 4.1.3 on 2023-08-21 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylvaultapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='borrowed',
        ),
    ]
