# Generated by Django 4.1.3 on 2023-09-02 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinylvaultapi', '0002_remove_record_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='spotify_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wishlistrecord',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='vinylvaultapi.record'),
        ),
    ]
