# Generated by Django 4.1.3 on 2023-09-05 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinylvaultapi', '0003_record_spotify_id_alter_wishlistrecord_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vinylvaultapi.genre'),
        ),
    ]
